# .github/workflows/ci.yml

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up CMake + GCC
      run: sudo apt-get update && sudo apt-get install -y cmake gcc

    - name: Build tests
      run: ./basicFreeRTOS.sh --build-tests

    - name: Run tests
      run: ./basicFreeRTOS.sh --run-tests